### ISSUE TITLE
Cannot find the class com.uber.marmaray.common.job.JsonHoodie in example

### ISSUE THREAD

**Issue by bestnaja** [uber/marmaray#19]
I follow the example but this class is missing com.uber.marmaray.common.job.JsonHoodie.
Could you update the example?

**Comment by esmioley** [comment]
Thanks for your interest @bestnaja. We're currently working on a more substantial example (parquet files on HDFS to Cassandra) and will be updating with that example shortly.

**Comment by bestnaja** [comment]
Cool. Thanks for information.

**Comment by bestnaja** [comment]
Thanks!!
